version: "3.8"

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - jaffle_shop_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.10
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  jaffle_shop_data: